### ISSUE TITLE
Toolbar subtitle is not set when using calligraphy

### ISSUE THREAD

**Issue by eriuzo** [chrisjenx/Calligraphy#280] opened 2016-04-25 13:55 UTC
Hi, I'm using Calligraphy the default way (initing in `Application` and overriding `attachBaseContext`)

Calling `toolbar.setSubtitle` doesn't work. If I commented the `attachBaseContext` override, it works normally.

Any suggestion for fixes or, unfortunately, hacks, is welcome.

LATE EDIT: 

> Calling `toolbar.setSubtitle` doesn't work.

By this I meant that the subtitle isn't displayed, and the title is vertically centered. (it's like subtitle view behavior is View.GONE)

**Comment by eriuzo** [comment] 2016-04-25 13:56
oh yeah, i'm using the support v7 toolbar, version 23.3.0 and calligraphy 2.2.0

**Comment by chrisjenx** [comment] 2016-04-25 17:17
@eriuzo how does your project differ to SampleApp? As that calls `setSubtitle` and works. (I tested this on the Sample by upgrading to the latest tools).

**Comment by eriuzo** [comment] 2016-04-26 06:51
I see you are wrapping the call using `postDelayed`, I will try this

**Comment by chrisjenx** [comment] 2016-04-26 06:56
Oh that was only done for the sample to show that you can add/remove post
inflation. You should be able to do it without the postDelayed.

**Comment by eriuzo** [comment] 2016-04-26 07:22
Weirdly, using `postDelayed` works. 

> You should be able to do it without the postDelayed.

I can't do it. I will try building your sample app on my config.

**Comment by chrisjenx** [comment] 2016-04-26 07:46
Oh really, it did work without post delayed, wonder if they changed
something in 23.3.0.

**Comment by eriuzo** [comment] 2016-04-26 07:51
Yeah, tried building your sample app on my machine, didn't work. All I did was just comment the handler code.

**Comment by eriuzo** [comment] 2016-04-26 07:57
No 23.2.1 didnt work either.

On the other hand, ctrl-clicking through the toolbar's `setSubtitle` method yield this:

```
/**
     * Set the subtitle of this toolbar.
     *
     * <p>Subtitles should express extended information about the current content.</p>
     *
     * @param subtitle Subtitle to set
     */
    public void setSubtitle(CharSequence subtitle) {
        if (!TextUtils.isEmpty(subtitle)) {
            if (mSubtitleTextView == null) {
                final Context context = getContext();
                mSubtitleTextView = new TextView(context);
                mSubtitleTextView.setSingleLine();
                mSubtitleTextView.setEllipsize(TextUtils.TruncateAt.END);
                if (mSubtitleTextAppearance != 0) {
                    mSubtitleTextView.setTextAppearance(context, mSubtitleTextAppearance);
                }
                if (mSubtitleTextColor != 0) {
                    mSubtitleTextView.setTextColor(mSubtitleTextColor);
                }
            }
            if (!isChildOrHidden(mSubtitleTextView)) {
                addSystemView(mSubtitleTextView, true);
            }
        } else if (mSubtitleTextView != null && isChildOrHidden(mSubtitleTextView)) {
            removeView(mSubtitleTextView);
            mHiddenViews.remove(mSubtitleTextView);
        }
        if (mSubtitleTextView != null) {
            mSubtitleTextView.setText(subtitle);
        }
        mSubtitleText = subtitle;
    }
```

CMIIW but it looks like it is being created programatically? What's your take on this

**Comment by chrisjenx** [comment] 2016-04-26 09:02
It is created programmatically which is why there is a Toolbar watcher in
the `CalligraphyFactory`, when the `Toolbar` is inflated we attach a
`viewTreeWatcher` to it to look for when it's finished being inflated, then
we forcibly set the titles to make sure they inflate then revert them back
to what they were.
I tested it across a whole load of emulators/api levels, and left it in the
snapshot for a while for people to test, but I guess there are still some
really weird edge cases. (Like yours).

I'm thinking more now, that I inflate my own version of the Toolbar to
proxy through the `setTitle` / `setSubtitle` calls, then I can 100% set the
correct typeface without any "watching" per-se, only downside is, that if
you extended the toolbar yourself (You shouldn't need to). That the proxing
would break...

Thoughts?

/cc @RomainPiel  for sanity checking

**Comment by eriuzo** [comment] 2016-04-26 10:22
Any chances this is because I use otf font? I will try another font.

Im not good at debugging other people's code but I will try experiment with local fork.

**Comment by chrisjenx** [comment] 2016-04-26 11:01
Oh entirely possible, otf barely work. Which is a shame as they are quite
handy.

**Comment by eriuzo** [comment] 2016-04-26 11:56
Well, calligraphy sample app uses ttf and it didnt work too in my case..

based on my limited debugging so far, the subtitle textview gets detected but the font doesnt get applied

**Comment by eriuzo** [comment] 2016-04-26 12:32
I have run out of coffee and decided to just use the workaround now (using postDelayed with at least 200ms delay)

However if you need more info let me know, cause this library is actually crucial to our app. Thanks!

**Comment by chrisjenx** [comment] 2016-04-26 12:32
OK, cool. I'll investigate.

**Comment by chrisjenx** [comment] 2016-04-26 17:13
Sure, I think I have a better way of handling this. Well at least an idea.

**Comment by tlubz** [comment] 2016-05-17 21:08
FYI This is happening for us too. we are using calligraphy v2.2.0, w/ appcompat-v7-23.4.0. It smashes any changes to the `Toolbar`'s subtitle that we make between when the `Activity` calls `setContentView` and when the next `onGlobalLayout` gets called on the toolbar's `ViewTreeObserver`.

As a workaround, we were able to attach a new `ViewTreeObserver.OnGlobalLayoutListener` to the `Toolbar` in `onCreate`, but after `setContentView`, which lets us set the subtitle to whatever we want immediately after calligraphy resets it.

Looking forward to a fix to avoid this hack!

**Comment by pdegand** [comment] 2016-07-03 19:59
Hi,
According to the code, there is no way setting the subtitle can work (appart with the bad `postDelayed` workaround)

The problem is that your `ToolbarLayoutListener` is created right when the view is inflated by `Activity.setContentView(int)`.
The constructor of this `ToolbarLayoutListener` is trying to save the actual subtitle of the Toolbar but the subtitle is always `null` because there is no way to set a subtitle before setting the content view on the activity.

What you should probably do, is always keep the layout listener but not adding the "dummy" subtitle.
This way, the listener will be called anytime a subtitle is set.

**Comment by chrisjenx** [comment] 2016-07-03 21:26
It's way more complicated than that.

**Comment by leofarage** [comment] 2016-09-01 19:37
I was having the same issue and came to the same conclusion as @pdegand.

To fix that, I added my own **OnGlobalLayoutListener** which is responsible for setting the subtitle (I know, it's ugly, but I tried using **postDelayed** but somehow I had to interact with the screen for the changes on the toolbar to show)

**Comment by leofarage** [comment] 2016-09-01 20:34
@chrisjenx what's the reason for on the ToolbarLayoutListener you keep the **originalSubtitle**? What's the reason for setting the originalSubtitle back? I'm curious about that because I think that's the reason for the subtitle not showing (or always keeping the value set via XML)

**Comment by chrisjenx** [comment] 2016-09-01 23:28
If we don't request the subtitle then it's never inflated by getting
setting and reverting we inflate the TextView set the attribute then revert
the text. I guess there could be a race condition, you shouldn't set the
subtitle until after onCreate or in XML.

**Comment by leofarage** [comment] 2016-09-02 17:04
I see -- alright!

**Comment by Tunous** [comment] 2016-09-11 14:46
I ran into similar issue and experimented with a simple change to attempt to fix this. It appears to be working correctly but I was only able to test it in emulator.

**Comment by Jawnnypoo** [comment] 2016-10-26 18:59
If anyone else comes across this issue, you can just do it with a call to `post()` on the Toolbar, no need for a delay. 
```
toolbar.post(new Runnable() {
                @Override
                public void run() {
                    toolbar.setSubtitle("something");
                }
            });
```

**Comment by v-grishechko** [comment] 2017-01-10 09:52
It's pity. But in my case, code by @Jawnnypoo not working. Device – Galaxy Nexus.

**Comment by DmitriyG1** [comment] 2017-03-16 18:16
I have the same issue. Checked in onPostCreate() and onResume(), the subtitle has text. But after some time the subtitle is null

**Comment by chrisjenx** [comment] 2017-03-16 23:11
How do you set text on the subtitles?

**Comment by Jawnnypoo** [comment] 2017-03-17 14:12
It would probably also work if you did it in a predraw listener. Something like:
```
    final OnPreDrawListener listener = new OnPreDrawListener() {
        @Override
        public boolean onPreDraw() {
            toolbar.getViewTreeObserver().removeOnPreDrawListener(this);
            toolbar.setSubtitle("blah");
            return true;
        }
    };
    toolbar.getViewTreeObserver().addOnPreDrawListener(listener);
```

**Comment by DmitriyG1** [comment] 2017-03-20 20:47
Calligraphy 2.2.0

Sample code, Kotlin 
```
import android.support.v7.app.AppCompatActivity
import android.support.v7.widget.Toolbar

class Test : AppCompatActivity() {
  private lateinit var toolbar: Toolbar
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.test)

    toolbar = findViewById(R.id.toolbar) as Toolbar
    setSupportActionBar(toolbar)
    toolbar.subtitle = "Test subtitle"

    val test = findViewById(R.id.test)
    test.setOnClickListener {
      // subtitle is null
      Log.d("Test", "OnClick() Subtitle: " + toolbar.subtitle)
    }
  }

  override fun onResume() {
    super.onResume()
    // subtitle is "Test subtitle"
    Log.d("Test", "onResume() Subtitle: " + toolbar.subtitle)
  }

  override fun attachBaseContext(newBase: Context) {
    super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase))
  }
}
```

Layout 
```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:app="http://schemas.android.com/apk/res-auto"
             android:layout_width="match_parent"
             android:layout_height="match_parent">

    <TextView
        android:id="@+id/test"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="?attr/actionBarSize"
        android:text="Test"/>

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:minHeight="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
        android:layout_gravity="top"
        />
</FrameLayout>
```

**Comment by Jawnnypoo** [comment] 2017-03-20 21:13
Is there a reason for `setSupportActionBar(toolbar)`? That may be causing the issue.

**Comment by chrisjenx** [comment] 2017-03-21 01:59
We only support the v7 toolbar not anything else.

**Closed** 2017-05-11 16:33 UTC
