### ISSUE TITLE
Memory Leak using 1.2.0

### ISSUE THREAD

**Issue by marcoRS** [chrisjenx/Calligraphy#102] opened 2014-12-08 05:54 UTC
I am seeing a memory leak using version 1.2.0. I didn't notice this until after I switched to AppCompat although that might not be the cause. As I switch between two fragments the memory starts accumulating. I have a typical setup where my subclassed Application class is calling CalligraphyConfig.initDefault() and a base Activity class that overrides attachBaseContext as:
@Override protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(new CalligraphyContextWrapper(newBase));
  }

In my fragments I use getActivity().getLayoutInflater() to inflate my views in onCreateView(). Has anyone been experiencing this? I also took a memory heap dump and it showed many instances of 
uk.co.chrisjenx.calligraphy.CalligraphyFactory. 
![screen shot 2014-12-07 at 9 40 10 pm](https://cloud.githubusercontent.com/assets/507510/5335243/5ae0d940-7e5a-11e4-809c-f73cb409ebf6.png)

Oddly the memory is only collected on a configuration change such as a rotation. I have verified that without the library the memory does not leak when I perform the same test which is just switching between two fragments that load bitmaps.

**Comment by chrisjenx** [comment] 2015-01-16 12:13
@marcoRS OK I may have to look into this more. I just haven't see this locally yet. :/

**Comment by marcoRS** [comment] 2015-01-17 20:45
I'm unfortunately still seeing this memory leak. The app I am working on is very photo intensive so when I  use Calligraphy I can quickly run out of memory. Please let me know if there's any way I can help you debug this. 

I follow the setup in the README except for the part related to lollipop where it mentions inflation as broken.

**Comment by chrisjenx** [comment] 2015-01-17 21:32
@marcoRS I've just removed the work around, forgot to do that. It's been fixed in 2.0.0. If you are able to upgrade and see if the leak is still a problem?

**Comment by marcoRS** [comment] 2015-01-17 22:50
The leak is still persistent unfortunately. I use the inflater that is provided in the fragment's onCreateView method where applicable.

**Comment by chrisjenx** [comment] 2015-01-17 23:18
Yeah remove the hack needed for Lollipop as thats now fixed.
I'll see if someone with better memory debugging skills can look into it.

**Comment by marcoRS** [comment] 2015-01-17 23:22
The problem seems to somehow be related to Android's appcompat Toolbar. When I analyze the memory consumption, one of the toolbars seems to stick around in memory when I use Calligraphy.

**Comment by chrisjenx** [comment] 2015-01-17 23:25
Ahh yeah that makes sense, that would happen. OK, yeah will have to think
how to improve the Toolbar code. Dang.

**Comment by marcoRS** [comment] 2015-01-22 18:17
I don't have a global Toolbar so after visiting a couple screens with their own toolbars, the memory ends up blowing up.

**Comment by dlew** [comment] 2015-01-22 22:07
Out of curiosity I fired up MAT and tried it on my own app and did not see any leaks there. I went deep into the app then backed out again.

I'm using dominator tree -> right click entry -> path to GC roots -> exclude weak references. The only instances of calligraphy objects I see are all linked to the current activity (not any of the ones that were created then destroyed).

Are you sure the `Toolbar` isn't sticking around because of some other GC root? It might be that Calligraphy is a red herring here, in that both might have the same GC root.

**Comment by chrisjenx** [comment] 2015-01-23 10:16
@dlew I can see a potential memory leak [here](https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java#L180-L190). If the toolbars are added and removed this watcher is never removed and would hold reference to the factory that created it. Although that would only be an issue if you added/removed toolbars inside of the activity multiple times. 

I can't see a case where reference would be kept past killing the activity.

**Comment by dlew** [comment] 2015-01-23 14:48
Just having run a test, adding/removing a Toolbar manually doesn't cause it to pick up Calligraphy's fonts. :) A bug for another time, or maybe I'm just not doing it right?

But yeah, the global layout listener could be causing problems for views inflated through Calligraphy. I'll run more tests when I have time.

**Comment by chrisjenx** [comment] 2015-01-23 14:51
Yeah adding/removing views pragmatically wouldn't. It's a known issue. If its inflated it should. I just need to investigate some more.

**Comment by marcoRS** [comment] 2015-01-26 21:38
The toolbar that is staying in memory is inflated separately from the fragment layout I create. @dlew Here is the memory analysis using MAT, I'm using it on the toolbar object and a fragmenttabhost that seems to also be sticking around and both are rather large:

![screen shot 2015-01-26 at 1 34 32 pm](https://cloud.githubusercontent.com/assets/507510/5908916/76740038-a560-11e4-9ce3-f74ea97a9140.png)

![screen shot 2015-01-26 at 1 35 15 pm](https://cloud.githubusercontent.com/assets/507510/5908922/82c070e2-a560-11e4-9893-2a5b20a3b54d.png)

I wish I understood better how to do memory analysis, do you have any blog post recommendations or books?

**Comment by dlew** [comment] 2015-01-26 22:12
This is a great talk about memory analysis: https://www.youtube.com/watch?v=_CruQY55HOk

Also that definitely looks like the `ViewTreeObserver` is what is sticking around.

**Comment by dlew** [comment] 2015-01-26 22:30
I've reproduced the issue. I'll double-fix this now.

**Comment by marcoRS** [comment] 2015-01-26 22:37
Awesome! I'm a big fan of your work btw. Your posts are very informative and I attended one of your presentations once at Andevcon. Thanks for all the great work!

**Comment by dlew** [comment] 2015-01-26 22:48
It'd be neat if you could pull the branch in #121 and test out if you're still seeing the leak on that branch.

Also, you're welcome. :)

**Comment by marcoRS** [comment] 2015-01-26 23:48
:-D The memory is being freed up now! :+1:

**Comment by chrisjenx** [comment] 2015-01-27 00:02
Nice work guys. I'll review tomorrow!

**Closed** 2015-01-28 10:04 UTC
