### ISSUE TITLE
Attribute have already defined

### ISSUE THREAD

**Issue by whmsysu** [chrisjenx/Calligraphy#169] opened 2015-05-11 22:03 UTC
I used Gradle to import calligraphy, but It seems conflict with actionbar sherlock I used in the project.Could you tell me how to solve the conflict. This conflict only happens when I using the 2.1.0.

**Comment by chrisjenx** [comment] 2015-05-13 16:14
I only have time to support the v7 `AppCompat` and `Toolbar`. If you find out what the cause is, feel free to send a PR, otherwise closing.

**Closed by chrisjenx** 2015-05-13 16:14 UTC
